name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ui:
    name: Test UI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install UI dependencies
      working-directory: ./ui
      run: npm ci
    
    - name: Run UI tests
      working-directory: ./ui
      run: npm test

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    needs: test-ui

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install API dependencies
      working-directory: ./api
      run: npm ci
    
    - name: Run API tests
      working-directory: ./api
      run: npm test